// Default chord assigned to each button, as an index into the `chords[]` /
// `chordNames[]` arrays in RiffMIDI.ino. Generated by flash_gui.py's chord
// picker -- edit by hand only if you're not using the GUI.
#ifndef CHORD_CONFIG_H
#define CHORD_CONFIG_H

#define GREEN_CHORD_INDEX 31  // Gsus4
#define RED_CHORD_INDEX 30  // F#sus4
#define YELLOW_CHORD_INDEX 35  // Bsus4
#define BLUE_CHORD_INDEX 10  // A#
#define ORANGE_CHORD_INDEX 13  // c#

#endif
