// Chord sets ("banks"): each row assigns a chord to all five buttons at
// once, as indices into the `chords[]` / `chordNames[]` arrays in
// RiffMIDI.ino. Up/Down select cycles through these sets on the device.
// Generated by flash_gui.py's chord set editor -- edit by hand only if
// you're not using the GUI.
#ifndef CHORD_SETS_H
#define CHORD_SETS_H

struct ChordSet {
  const char* name;
  uint8_t green;
  uint8_t red;
  uint8_t yellow;
  uint8_t blue;
  uint8_t orange;
};

const ChordSet chordSets[] = {
  {"Verse", 0, 7, 50, 51, 52},  // C, G, BV1, BV2, BV3
  {"Chorus", 0, 0, 0, 53, 54},  // C, C, C, BVS1, BVS2
  {"Bloody Valentine", 0, 0, 56, 57, 58},  // C, C, MGK1, MGK2, MGK3
};

const uint8_t numChordSets = sizeof(chordSets) / sizeof(ChordSet);

#endif
