// Chord sets ("banks"): each row assigns a chord to all five buttons at
// once, as indices into the `chords[]` / `chordNames[]` arrays in
// RiffMIDI.ino. Up/Down select cycles through these sets on the device.
// Generated by flash_gui.py's chord set editor -- edit by hand only if
// you're not using the GUI.
#ifndef CHORD_SETS_H
#define CHORD_SETS_H

struct ChordSet {
  uint8_t green;
  uint8_t red;
  uint8_t yellow;
  uint8_t blue;
  uint8_t orange;
};

const ChordSet chordSets[] = {
  {0, 7, 22, 5, 11},  // Set 1: C, G, a#, F, B
  {29, 0, 0, 0, 0},  // Set 2: Fsus4, C, C, C, C
};

const uint8_t numChordSets = sizeof(chordSets) / sizeof(ChordSet);

#endif
