// Chord sets ("banks"): each row assigns a chord to all five buttons at
// once, as indices into the `chords[]` / `chordNames[]` arrays in
// RiffMIDI.ino. Up/Down select cycles through these sets on the device.
// Generated by flash_gui.py's chord set editor -- edit by hand only if
// you're not using the GUI.
#ifndef CHORD_SETS_H
#define CHORD_SETS_H

struct ChordSet {
  uint8_t green;
  uint8_t red;
  uint8_t yellow;
  uint8_t blue;
  uint8_t orange;
};

const ChordSet chordSets[] = {
  {0, 7, 38, 39, 40},  // Set 1: C, G, BV1, BV2, BV3
  {0, 0, 0, 41, 42},  // Set 2: C, C, C, BVS1, BVS2
};

const uint8_t numChordSets = sizeof(chordSets) / sizeof(ChordSet);

#endif
