#!/usr/bin/env python3
"""GUI for RiffMIDI: assign chords to the five strum buttons and program
the board step by step -- flash the atmega16u2 to Arduino/USB-Serial mode,
compile and upload the sketch, then flash the atmega16u2 back to MIDI mode.
Each step is a separate button so you can retry a step (e.g. picking the
serial port again) without redoing the others.
"""

import json
import os
import re
import shlex
import shutil
import subprocess
import threading
import tkinter as tk
from tkinter import messagebox, scrolledtext, ttk

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INO_PATH = os.path.join(SCRIPT_DIR, "RiffMIDI.ino")
CHORD_SETS_PATH = os.path.join(SCRIPT_DIR, "chord_sets.h")
CONTROL_SURFACE_LIB = os.path.join(SCRIPT_DIR, "libraries", "Control-Surface")
BUILD_CACHE_DIR = os.path.join(SCRIPT_DIR, ".build-cache")
FQBN = "arduino:avr:mega"

ARDUINO_HEX = os.path.join(SCRIPT_DIR, "Arduino-usbserial-atmega16u2-Mega2560-Rev3.hex")
MIDI_HEX = os.path.join(SCRIPT_DIR, "arduino_midi.hex")

# (button label, ChordSet struct field name)
BUTTON_SLOTS = [
    ("Green", "green"),
    ("Red", "red"),
    ("Yellow", "yellow"),
    ("Blue", "blue"),
    ("Orange", "orange"),
]


def find_tool(name, extra_candidates=()):
    path = shutil.which(name)
    if path:
        return path
    for candidate in extra_candidates:
        if os.path.isfile(candidate):
            return candidate
    return None


def find_dfu_programmer():
    return find_tool(
        "dfu-programmer",
        ("/opt/homebrew/bin/dfu-programmer", "/usr/local/bin/dfu-programmer"),
    )


def find_arduino_cli():
    return find_tool(
        "arduino-cli",
        ("/opt/homebrew/bin/arduino-cli", "/usr/local/bin/arduino-cli"),
    )


def parse_chord_names(ino_path):
    """Pull the chordNames[] string list out of RiffMIDI.ino, in order."""
    with open(ino_path, "r") as f:
        text = f.read()
    match = re.search(r"chordNames\[\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not match:
        return []
    return re.findall(r'"([^"]*)"', match.group(1))


def read_chord_sets(path):
    """Parse the chordSets[] initializer rows out of chord_sets.h, in order.
    Returns a list of dicts with the BUTTON_SLOTS field names as keys."""
    if not os.path.isfile(path):
        return []
    with open(path, "r") as f:
        text = f.read()
    match = re.search(r"chordSets\[\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not match:
        return []
    rows = re.findall(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}", match.group(1))
    fields = [f for _, f in BUTTON_SLOTS]
    return [dict(zip(fields, (int(v) for v in row))) for row in rows]


def write_chord_sets(path, sets, chord_names):
    lines = [
        '// Chord sets ("banks"): each row assigns a chord to all five buttons at',
        "// once, as indices into the `chords[]` / `chordNames[]` arrays in",
        "// RiffMIDI.ino. Up/Down select cycles through these sets on the device.",
        "// Generated by flash_gui.py's chord set editor -- edit by hand only if",
        "// you're not using the GUI.",
        "#ifndef CHORD_SETS_H",
        "#define CHORD_SETS_H",
        "",
        "struct ChordSet {",
        "  uint8_t green;",
        "  uint8_t red;",
        "  uint8_t yellow;",
        "  uint8_t blue;",
        "  uint8_t orange;",
        "};",
        "",
        "const ChordSet chordSets[] = {",
    ]
    for i, s in enumerate(sets):
        values = ", ".join(str(s[f]) for _, f in BUTTON_SLOTS)
        names = ", ".join(chord_names[s[f]] if 0 <= s[f] < len(chord_names) else "?" for _, f in BUTTON_SLOTS)
        lines.append(f"  {{{values}}},  // Set {i + 1}: {names}")
    lines += [
        "};",
        "",
        "const uint8_t numChordSets = sizeof(chordSets) / sizeof(ChordSet);",
        "",
        "#endif",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def format_set_summary(index, chord_set, chord_names):
    names = ", ".join(
        chord_names[chord_set[f]] if 0 <= chord_set[f] < len(chord_names) else "?"
        for _, f in BUTTON_SLOTS
    )
    return f"Set {index + 1}: {names}"


def list_serial_ports(arduino_cli):
    try:
        result = subprocess.run(
            [arduino_cli, "board", "list", "--format", "json"],
            capture_output=True, text=True, timeout=20,
        )
        data = json.loads(result.stdout or "{}")
        ports = [p["port"]["address"] for p in data.get("detected_ports", [])]
        return sorted(ports)
    except Exception:
        return []


def build_dfu_shell_cmd(dfu, hex_path):
    # dfu-programmer's "erase" exits non-zero whenever it actually had to
    # erase non-blank memory (even though the erase itself succeeds), so
    # its exit code must not gate the rest of the chain.
    return (
        f"{shlex.quote(dfu)} atmega16u2 erase; "
        f"{shlex.quote(dfu)} atmega16u2 flash {shlex.quote(hex_path)} && "
        f"{shlex.quote(dfu)} atmega16u2 reset"
    )


def run_privileged_shell(shell_cmd, timeout=120):
    applescript_string = shell_cmd.replace("\\", "\\\\").replace('"', '\\"')
    osascript_cmd = [
        "osascript", "-e",
        f'do shell script "{applescript_string}" with administrator privileges',
    ]
    try:
        result = subprocess.run(osascript_cmd, capture_output=True, text=True, timeout=timeout)
        return result.returncode, (result.stdout or "") + (result.stderr or "")
    except subprocess.TimeoutExpired:
        return -1, "Timed out."
    except Exception as exc:  # noqa: BLE001
        return -1, str(exc)


class ChordSetDialog(tk.Toplevel):
    """Modal dialog to pick/edit the 5 chords (one per button) for one set."""

    def __init__(self, parent, chord_names, title, initial=None):
        super().__init__(parent)
        self.title(title)
        self.resizable(False, False)
        self.result = None
        self.chord_names = chord_names

        initial = initial or {f: 0 for _, f in BUTTON_SLOTS}

        self.vars = {}
        for label, field in BUTTON_SLOTS:
            row = tk.Frame(self)
            row.pack(fill="x", padx=10, pady=4)
            tk.Label(row, text=f"{label}:", width=8, anchor="w").pack(side="left")
            var = tk.StringVar()
            idx = initial[field]
            if chord_names and 0 <= idx < len(chord_names):
                var.set(chord_names[idx])
            combo = ttk.Combobox(row, textvariable=var, values=chord_names, state="readonly", width=30)
            combo.pack(side="left")
            self.vars[field] = var

        btn_row = tk.Frame(self)
        btn_row.pack(fill="x", padx=10, pady=(6, 10))
        tk.Button(btn_row, text="Cancel", command=self.destroy).pack(side="right")
        tk.Button(btn_row, text="OK", command=self._on_ok).pack(side="right", padx=(0, 8))

        self.transient(parent)
        self.grab_set()

    def _on_ok(self):
        result = {}
        for _, field in BUTTON_SLOTS:
            name = self.vars[field].get()
            result[field] = self.chord_names.index(name) if name in self.chord_names else 0
        self.result = result
        self.destroy()


class FlashApp:
    def __init__(self, root):
        self.root = root
        root.title("RiffMIDI Board Programmer")
        root.resizable(False, False)

        self.dfu_path = find_dfu_programmer()
        self.arduino_cli_path = find_arduino_cli()
        self.chord_names = parse_chord_names(INO_PATH)
        self.all_buttons = []
        self.chord_sets = read_chord_sets(CHORD_SETS_PATH) or [{f: 0 for _, f in BUTTON_SLOTS}]

        pad = {"padx": 12, "pady": 6}

        # --- Chord sets ---
        sets_frame = tk.LabelFrame(root, text="1. Chord Sets (Up/Down select cycles these on the board)", padx=10, pady=10)
        sets_frame.pack(fill="x", **pad)

        list_row = tk.Frame(sets_frame)
        list_row.pack(fill="x")
        self.sets_listbox = tk.Listbox(list_row, width=60, height=6, exportselection=False)
        self.sets_listbox.pack(side="left", fill="x", expand=True)

        set_btn_col = tk.Frame(list_row)
        set_btn_col.pack(side="left", padx=(8, 0))
        self.add_set_button = self._add_button(set_btn_col, "Add Set", self.add_set, fill="x", pady=2)
        self.edit_set_button = self._add_button(set_btn_col, "Edit Set", self.edit_set, fill="x", pady=2)
        self.delete_set_button = self._add_button(set_btn_col, "Delete Set", self.delete_set, fill="x", pady=2)
        self.move_up_button = self._add_button(set_btn_col, "Move Up", self.move_set_up, fill="x", pady=2)
        self.move_down_button = self._add_button(set_btn_col, "Move Down", self.move_set_down, fill="x", pady=2)

        if not self.chord_names:
            tk.Label(sets_frame, text="Could not read chord list from RiffMIDI.ino.", fg="red").pack(anchor="w")

        self.save_sets_button = self._add_button(
            sets_frame, "Save Sets to chord_sets.h", self.save_sets, anchor="w", pady=(8, 0)
        )

        self._refresh_sets_listbox()

        # --- Step 2: flash Arduino firmware ---
        step2_frame = tk.LabelFrame(root, text="2. Flash Arduino (USB-Serial) Firmware", padx=10, pady=10)
        step2_frame.pack(fill="x", **pad)
        tk.Label(step2_frame, text="Puts the board in upload mode so the sketch can be sent to it.").pack(anchor="w")
        self.flash_arduino_button = self._add_button(
            step2_frame, "Flash Arduino Firmware...", self.flash_arduino_firmware, anchor="w", pady=(6, 0)
        )

        # --- Step 3: upload sketch ---
        step3_frame = tk.LabelFrame(root, text="3. Compile && Upload Sketch", padx=10, pady=10)
        step3_frame.pack(fill="x", **pad)

        port_row = tk.Frame(step3_frame)
        port_row.pack(fill="x")
        tk.Label(port_row, text="Serial port:").pack(side="left")
        self.port_var = tk.StringVar()
        self.port_combo = ttk.Combobox(port_row, textvariable=self.port_var, values=[], width=30)
        self.port_combo.pack(side="left", padx=(6, 6))
        self.refresh_ports_button = self._add_button(
            port_row, "Refresh Ports", self.refresh_ports, side="left"
        )

        self.upload_button = self._add_button(
            step3_frame, "Compile && Upload", self.upload_sketch, anchor="w", pady=(6, 0)
        )

        # --- Step 4: flash MIDI firmware ---
        step4_frame = tk.LabelFrame(root, text="4. Flash MIDI Firmware", padx=10, pady=10)
        step4_frame.pack(fill="x", **pad)
        tk.Label(step4_frame, text="Restores the board to a class-compliant MIDI controller.").pack(anchor="w")
        self.flash_midi_button = self._add_button(
            step4_frame, "Flash MIDI Firmware...", self.flash_midi_firmware, anchor="w", pady=(6, 0)
        )

        warnings = []
        if self.dfu_path is None:
            warnings.append("dfu-programmer not found on PATH.")
        if self.arduino_cli_path is None:
            warnings.append("arduino-cli not found on PATH (needed for step 3).")
        if not os.path.isfile(ARDUINO_HEX):
            warnings.append(f"Missing {os.path.basename(ARDUINO_HEX)}.")
        if not os.path.isfile(MIDI_HEX):
            warnings.append(f"Missing {os.path.basename(MIDI_HEX)}.")
        if warnings:
            tk.Label(root, text="\n".join(warnings), fg="red", justify="left").pack(anchor="w", **pad)

        tk.Label(root, text="Log:").pack(anchor="w", padx=12)
        self.log = scrolledtext.ScrolledText(root, width=80, height=18, state="disabled")
        self.log.pack(padx=12, pady=(0, 12))

        self.refresh_ports()

    def _add_button(self, parent, text, command, **pack_kwargs):
        btn = tk.Button(parent, text=text, command=command)
        btn.pack(**pack_kwargs)
        self.all_buttons.append(btn)
        return btn

    # ---------- shared helpers ----------

    def append_log(self, text):
        self.log.configure(state="normal")
        self.log.insert(tk.END, text)
        self.log.see(tk.END)
        self.log.configure(state="disabled")

    def set_buttons_enabled(self, enabled):
        state = "normal" if enabled else "disabled"
        for btn in self.all_buttons:
            btn.configure(state=state)

    def _refresh_sets_listbox(self):
        self.sets_listbox.delete(0, tk.END)
        for i, s in enumerate(self.chord_sets):
            self.sets_listbox.insert(tk.END, format_set_summary(i, s, self.chord_names))

    def _selected_set_index(self):
        selection = self.sets_listbox.curselection()
        return selection[0] if selection else None

    def _run_dfu_flash(self, hex_path, label):
        if self.dfu_path is None:
            messagebox.showerror("dfu-programmer not found", "Install it with: brew install dfu-programmer")
            return
        if not os.path.isfile(hex_path):
            messagebox.showerror("Missing file", f"Could not find {hex_path}")
            return

        proceed = messagebox.askokcancel(
            "Put board in DFU mode",
            "Press the DFU/reset button on the atmega16u2 now, then click OK.\n\nClick Cancel to abort.",
        )
        if not proceed:
            return

        self.set_buttons_enabled(False)
        self.append_log(f"\n=== Flashing '{label}' ({os.path.basename(hex_path)}) ===\n")
        threading.Thread(target=self._dfu_flash_thread, args=(hex_path, label), daemon=True).start()

    def _dfu_flash_thread(self, hex_path, label):
        shell_cmd = build_dfu_shell_cmd(self.dfu_path, hex_path)
        returncode, output = run_privileged_shell(shell_cmd)
        self.root.after(0, self._dfu_flash_done, returncode, output, label)

    def _dfu_flash_done(self, returncode, output, label):
        self.append_log(output if output else "(no output)\n")
        self.set_buttons_enabled(True)
        if returncode == 0:
            self.append_log(f"=== '{label}' flashed successfully ===\n")
            messagebox.showinfo("Done", f"'{label}' flashed successfully.")
        else:
            self.append_log(f"=== Flash FAILED (exit code {returncode}) ===\n")
            if "User canceled" not in output:
                messagebox.showerror("Flash failed", "Flashing failed. See log for details.")

    # ---------- step 1: manage chord sets ----------

    def add_set(self):
        if not self.chord_names:
            messagebox.showerror("Cannot add set", "Chord list wasn't loaded from RiffMIDI.ino.")
            return
        dialog = ChordSetDialog(self.root, self.chord_names, "Add Chord Set")
        self.root.wait_window(dialog)
        if dialog.result is not None:
            self.chord_sets.append(dialog.result)
            self._refresh_sets_listbox()
            self.sets_listbox.selection_set(len(self.chord_sets) - 1)

    def edit_set(self):
        index = self._selected_set_index()
        if index is None:
            messagebox.showerror("No set selected", "Select a chord set to edit.")
            return
        dialog = ChordSetDialog(self.root, self.chord_names, f"Edit Chord Set {index + 1}", self.chord_sets[index])
        self.root.wait_window(dialog)
        if dialog.result is not None:
            self.chord_sets[index] = dialog.result
            self._refresh_sets_listbox()
            self.sets_listbox.selection_set(index)

    def delete_set(self):
        index = self._selected_set_index()
        if index is None:
            messagebox.showerror("No set selected", "Select a chord set to delete.")
            return
        if len(self.chord_sets) <= 1:
            messagebox.showerror("Cannot delete", "At least one chord set is required.")
            return
        del self.chord_sets[index]
        self._refresh_sets_listbox()

    def move_set_up(self):
        index = self._selected_set_index()
        if index is None or index == 0:
            return
        self.chord_sets[index - 1], self.chord_sets[index] = self.chord_sets[index], self.chord_sets[index - 1]
        self._refresh_sets_listbox()
        self.sets_listbox.selection_set(index - 1)

    def move_set_down(self):
        index = self._selected_set_index()
        if index is None or index >= len(self.chord_sets) - 1:
            return
        self.chord_sets[index + 1], self.chord_sets[index] = self.chord_sets[index], self.chord_sets[index + 1]
        self._refresh_sets_listbox()
        self.sets_listbox.selection_set(index + 1)

    def save_sets(self):
        if not self.chord_names:
            messagebox.showerror("Cannot save", "Chord list wasn't loaded from RiffMIDI.ino.")
            return
        write_chord_sets(CHORD_SETS_PATH, self.chord_sets, self.chord_names)
        self.append_log(f"\n=== Wrote chord_sets.h with {len(self.chord_sets)} set(s) ===\n")
        messagebox.showinfo("Saved", "chord_sets.h updated with your chord sets.")

    # ---------- step 2: flash Arduino firmware ----------

    def flash_arduino_firmware(self):
        self._run_dfu_flash(ARDUINO_HEX, "Arduino (USB-Serial) Firmware")

    # ---------- step 3: upload sketch ----------

    def refresh_ports(self):
        if self.arduino_cli_path is None:
            return
        ports = list_serial_ports(self.arduino_cli_path)
        self.port_combo.configure(values=ports)
        if ports and self.port_var.get() not in ports:
            self.port_var.set(ports[0])

    def upload_sketch(self):
        if self.arduino_cli_path is None:
            messagebox.showerror("arduino-cli not found", "Install it with: brew install arduino-cli")
            return
        port = self.port_var.get().strip()
        if not port:
            messagebox.showerror("No port selected", "Pick the board's serial port (use Refresh Ports if needed).")
            return

        self.set_buttons_enabled(False)
        self.append_log(f"\n=== Compiling and uploading sketch to {port} ===\n")
        threading.Thread(target=self._upload_thread, args=(port,), daemon=True).start()

    def _upload_thread(self, port):
        cmd = [
            self.arduino_cli_path, "compile",
            "--fqbn", FQBN,
            "--library", CONTROL_SURFACE_LIB,
            "--build-path", BUILD_CACHE_DIR,
            "--upload", "-p", port,
            SCRIPT_DIR,
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            output = (result.stdout or "") + (result.stderr or "")
            self.root.after(0, self._upload_done, result.returncode, output)
        except subprocess.TimeoutExpired:
            self.root.after(0, self._upload_done, -1, "Timed out compiling/uploading.")
        except Exception as exc:  # noqa: BLE001
            self.root.after(0, self._upload_done, -1, str(exc))

    def _upload_done(self, returncode, output):
        self.append_log(output if output else "(no output)\n")
        self.set_buttons_enabled(True)
        if returncode == 0:
            self.append_log("=== Sketch uploaded successfully ===\n")
            messagebox.showinfo("Done", "Sketch uploaded successfully.")
        else:
            self.append_log("=== Compile/upload FAILED ===\n")
            messagebox.showerror("Upload failed", "Compile/upload failed. See log for details.")

    # ---------- step 4: flash MIDI firmware ----------

    def flash_midi_firmware(self):
        self._run_dfu_flash(MIDI_HEX, "MIDI Firmware")


def main():
    root = tk.Tk()
    FlashApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
