// Note sets ("banks") for the 5 High (single-note) buttons: each row
// assigns one note to each button at once. Ok/Back cycles through these
// sets on the device (separate from Up/Down, which cycles chord sets).
// Generated by flash_gui.py's note set editor -- edit by hand only if
// you're not using the GUI.
#ifndef NOTE_SETS_H
#define NOTE_SETS_H

struct NoteSet {
  const char* name;
  MIDI_Notes::Note green;
  MIDI_Notes::Note red;
  MIDI_Notes::Note yellow;
  MIDI_Notes::Note blue;
  MIDI_Notes::Note orange;
};

const NoteSet noteSets[] = {
  {"Lead", MIDI_Notes::C, MIDI_Notes::G, MIDI_Notes::A, MIDI_Notes::F, MIDI_Notes::Bb},
  {"Verse", MIDI_Notes::B, MIDI_Notes::Db, MIDI_Notes::Ab, MIDI_Notes::B, MIDI_Notes::C},
  {"MGK bridge 1", MIDI_Notes::B, MIDI_Notes::Eb, MIDI_Notes::A, MIDI_Notes::Ab, MIDI_Notes::B},
};

const uint8_t numNoteSets = sizeof(noteSets) / sizeof(NoteSet);

#endif
